export const testeColaboradores = [
  {
    id: 201,
    nome: "João Silva",
    departamento: "Operações",
    cargo: "Técnico de Manutenção",
    dataInicio: "2022-01-10",
  },
  {
    id: 202,
    nome: "Maria Oliveira",
    departamento: "Recursos Humanos",
    cargo: "Analista de RH",
    dataInicio: "2021-03-15",
  },
  {
    id: 203,
    nome: "Carlos Santos",
    departamento: "Financeiro",
    cargo: "Assistente Financeiro",
    dataInicio: "2020-06-05",
  },
  {
    id: 204,
    nome: "Fernanda Lima",
    departamento: "Marketing",
    cargo: "Coordenadora de Marketing",
    dataInicio: "2023-09-12",
  },
  {
    id: 205,
    nome: "Lucas Almeida",
    departamento: "Tecnologia da Informação",
    cargo: "Desenvolvedor Full Stack",
    dataInicio: "2022-11-01",
  },
  {
    id: 206,
    nome: "Juliana Costa",
    departamento: "Comercial",
    cargo: "Executiva de Vendas",
    dataInicio: "2019-08-20",
  },
  {
    id: 207,
    nome: "Rafael Gomes",
    departamento: "Logística",
    cargo: "Supervisor de Logística",
    dataInicio: "2018-05-02",
  },
  {
    id: 208,
    nome: "Patrícia Mendes",
    departamento: "Atendimento",
    cargo: "Suporte ao Cliente",
    dataInicio: "2021-07-18",
  },
  {
    id: 209,
    nome: "Bruno Ferreira",
    departamento: "Produção",
    cargo: "Operador de Máquinas",
    dataInicio: "2017-04-09",
  },
  {
    id: 210,
    nome: "Aline Rocha",
    departamento: "Jurídico",
    cargo: "Advogada",
    dataInicio: "2020-02-25",
  },
];
